---
apiVersion: v1
kind: Service
metadata:
  name: moderator
spec:
  selector:
    app: moderator
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

  ---
apiVersion: v1
kind: Service
metadata:
  name: moderator-canary
spec:
  selector:
    app: moderator
  ports:
    - port: 8080
      targetPort: 8080
