apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
spec:
  description: Project for testt repo with only Deployment allowed
  sourceRepos:
    - https://github.com/udemykcloud/Argocd.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: batch
      kind: Job
    - group: ""
      kind: Service
    - group: ""
      kind: Secret

