apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: ap-south-1
  version: "1.32"

vpc:
  nat:
    gateway: Single # Cost-optimized: Single NAT Gateway for all subnets

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: false # Nodes in public subnets
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
