apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
spec:
  description: Project for test repo with all clusters and namespaces allowed
  sourceRepos:
    - https://github.com/udemykcloud/Argocd.git

  destinations:
    # ✅ Dev cluster (us-east-1)
    - namespace: '*'
      server: https://1440EF309B7D8B599579E7FFC69D84F2.gr7.us-east-1.eks.amazonaws.com

    # ✅ Prod cluster (ap-south-1)
    - namespace: '*'
      server: https://A62F1AB01F99B8668087E1A776089FE2.yl4.ap-south-1.eks.amazonaws.com

  # Allow creating Namespaces and all namespaced resources
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"