apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

resources:
- ../../base

patches:
- path: replicas.yaml
- path: rollout-service-names-patch.yaml
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: guestbook-ui-ingress



images:
- name: udemykcloud534/guestbook
  newName: udemykcloud534/guestbook
  newTag: staging-20250814-120725-aa11d00
