apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

resources:
- ../../base

patches:
- path: replicas.yaml
- path: rollout-service-names-patch.yaml
#- path: ingress-patch.yaml


images:
- name: udemykcloud534/guestbook
  newName: udemykcloud534/guestbook
  newTag: staging-20250814-092925-711a6bb
