apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod

resources:
- ../../base

patches:
  # Inline replica patch
  - target:
      kind: Rollout
      name: moderator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  # Inline rollout service names patch
  - target:
      kind: Rollout
      name: moderator
    patch: |-
      - op: replace
        path: /spec/strategy/blueGreen
        value:
          activeService: prod-moderator
          previewService: prod-moderator-canary
          autoPromotionEnabled: false
          autoPromotionSeconds: 30
          scaleDownDelaySeconds: 10

