apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: moderator
  template:
    metadata:
      labels:
        app: moderator
    spec:
      containers:
        - image: udemykcloud534/moderator:staging-4ad95226f7c1fb4ff1532e01c0aa44f31cc7a2a7
          name: moderator
          ports:
            - containerPort: 80
