apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod

resources:
- ../../base

patches:
- path: replicas.yaml
- path: rollout-service-names-patch.yaml
- target:
    kind: Ingress
    name: guestbook-ui-ingress
  path: ingress-patch.yaml
