apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stg-
namespace: stg

resources:
- ../../base

images:
- name: udemykcloud534/guestbook
  newName: udemykcloud534/guestbook
  newTag: yellow

patches:
  # Inline replica patch
  - target:
      kind: Rollout
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  # Inline rollout service names patch
  - target:
      kind: Rollout
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/strategy/blueGreen
        value:
          activeService: stg-guestbook-ui
          previewService: stg-guestbook-ui-canary
          autoPromotionEnabled: false
          autoPromotionSeconds: 30
          scaleDownDelaySeconds: 10

  # Inline ingress patch
  - target:
      kind: Ingress
      name: guestbook-ui-ingress
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      - op: replace
        path: /spec/rules
        value:
          - host: guestbook.local
            http:
              paths:
                - path: /stg(/|$)(.*)
                  pathType: Prefix
                  backend:
                    service:
                      name: stg-guestbook-ui
                      port:
                        number: 80
                - path: /stg-preview(/|$)(.*)
                  pathType: Prefix
                  backend:
                    service:
                      name: stg-guestbook-ui-canary
                      port:
                        number: 80
  - target:
      kind: Rollout
      name: guestbook-ui
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: MODERATOR_URL
            value: "http://stg-moderator:8080"

